### ISSUE TITLE
目录名添加Chapter

### ISSUE THREAD

**Issue by CharlieZhao95** [shihai1991/CPython-Internals#2]
章节按Chapter划分，可以保证文件的顺序更方便阅读
```
Chapter1
    Chapter1.1
    ...
```

**Comment by shihai1991** [comment]
你说markdown文件名上加一下chapter前缀还是说就以chapter为文件或者目录名？

**Comment by CharlieZhao95** [comment]
> 你说markdown文件名上加一下chapter前缀还是说就以chapter为文件或者目录名？

为目录和文件增加Chapter的前缀，这样可能看起来更有条理一些

**Comment by shihai1991** [comment]
好，我建议大家都翻译差不多了在统一刷新一下。

**Comment by shihai1991** [comment]
感谢赵羽同学提的建议，已更新
