### ISSUE TITLE
制定更清晰的翻译规范

### ISSUE THREAD

**Issue by CharlieZhao95** [shihai1991/CPython-Internals#3]
原文格式还是非常清晰的，但部分表格、数据使用markdown展现并不是很合适。

* 格式规范
    * 三线表：直接使用markdown的内置表格；
    * Notes/See Also： 分割线+**顶格加粗**+结束换行。
 
* 翻译规范
    * **尽量保证作者的原意，不添加个人的观点；**
    * 对于部分术语可能保持原文更好，例如Code Object或Frame Object强行翻译成代码对象/帧对象反而不好理解，参考《Python源码剖析》对于两者其实未作翻译。

**Comment by lijunchen** [comment]
还有标点的规范，例如参考 https://github.com/sparanoid/chinese-copywriting-guidelines

**Comment by shihai1991** [comment]
初始化提交了一个，大家帮忙看看还要补充哪些规范。https://github.com/shihai1991/CPython-Internals/pull/4/files

**Comment by CharlieZhao95** [comment]
Note的格式：大家看下这样是否美观，或者有没有其他建议。
![image](https://user-images.githubusercontent.com/68189100/160048463-4fa6ede8-7258-4c46-8812-f4e25056c6f8.png)

![image](https://user-images.githubusercontent.com/68189100/160048380-a56d0cff-fe0e-4d47-a164-4b2b824e32fd.png)

**Comment by lijunchen** [comment]
Note 看看能不能用这个 https://docs.gitbook.com/editing-content/rich-content/with-command-palette#hints-and-callouts

**Comment by CharlieZhao95** [comment]
> Note 看看能不能用这个 https://docs.gitbook.com/editing-content/rich-content/with-command-palette#hints-and-callouts

确实借用 gitbook 的一些能力排版会更好，稍后我会提交一节看看 Markdown 下的效果。

**Comment by CharlieZhao95** [comment]
> 确实借用 gitbook 的一些能力排版会更好，稍后我会提交一节看看 Markdown 下的效果。

参考PR: https://github.com/shihai1991/CPython-Internals/pull/5
可能 review 时也借用gitbook的能力会好些，不然排版的效果看不出来。

**Comment by shihai1991** [comment]
还有翻译如下语句，ref: #1
```
1. xxxx
2. xxxx
```
这种最后是不是需要加个`。`或者`;`?

**Comment by shihai1991** [comment]
图片存放和命名需要定一下。https://github.com/shihai1991/CPython-Internals/pull/5#discussion_r835933717

**Comment by CharlieZhao95** [comment]
> 还有翻译如下语句，ref: #1
> 
> ```
> 1. xxxx
> 2. xxxx
> ```
> 
> 这种最后是不是需要加个`。`或者`;`?

有序和无序列表未结束前使用 `;` , 结束时使用 `。`
* start；
* do something；
* end。
一般论文格式是这样，大家有其他想法也可以提出。

**Comment by shihai1991** [comment]
> > 还有翻译如下语句，ref: #1
> > ```
> > 1. xxxx
> > 2. xxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这种最后是不是需要加个`。`或者`;`?
> 
> 有序和无序列表未结束前使用 `;` , 结束时使用 `。`
> 
> * start；
> * do something；
> * end。
> 
> 一般标准的论文格式是这样，大家有其他想法也可以提出。

+1

**Comment by shihai1991** [comment]
赵羽的有些建议我#4里面没添加进去，不知道是网络问题还是我忘了。后面在重新提PR刷新。
https://github.com/shihai1991/CPython-Internals/pull/4#discussion_r834908673

**Comment by shihai1991** [comment]
后面有更新在创建新的issue。
