### ISSUE TITLE
第 5.1 节末尾的 Note 中，MacOS 下的可执行文件名有误

### ISSUE THREAD

**Issue by nukemiko** [shihai1991/CPython-Internals#52]
如图，应当是 `./python`，后面没有 `.exe`。

![图片](https://user-images.githubusercontent.com/53572814/204193604-d4b6a85f-b7a5-4f2f-93d9-86758e5cbdb7.png)

**Comment by shihai1991** [comment]
感谢review，估计作者自己也写错了。
![image](https://user-images.githubusercontent.com/9103416/204196448-d2baf4f2-ebf4-41fb-82d0-1698cdf49191.png)
